# Generated by Django 5.0.2 on 2025-04-24 09:39

import notices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='notices/attachments/', validators=[notices.models.validate_pdf]),
        ),
    ]
